notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master

before_script:
 - chmod +x travis.sh

script: ./travis.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
