language: ruby

sudo: false

cache: bundler

rvm:
- 2.2.2

notifications:
  email:
    on_success: never
    on_failure: never

before_script:
  - chmod +x ./travis.sh

install:
  - gem install jekyll html-proofer

script: ./travis.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
