notifications:
  email:
    on_success: never
    on_failure: change

language: ruby
rvm:
  - 2.1

branches:
  only:
    - master

sudo: false

script:
  echo 'Testing travis...'
  bundle exec jekyll build
  bundle exec htmlproofer ./_site --disable-external --only-4xx --check-favicon --check-html
